apiVersion: apps/v1
kind: Deployment
metadata:
  name: autodeploy54543
  labels:
    app: autodeploy54543
  namespace: namespace-workflow-1708371851171
spec:
  replicas: 1
  selector:
    matchLabels:
      app: autodeploy54543
  template:
    metadata:
      labels:
        app: autodeploy54543
    spec:
      containers:
        - name: autodeploy54543
          image: acrworkflow1708371851171.azurecr.io/image-workflow-1708371851171:latest
          ports:
            - containerPort: 5000