apiVersion: v1
kind: Service
metadata:
  name: autodeploy54543
  namespace: namespace-workflow-1708371851171
spec:
  type: LoadBalancer
  selector:
    app: autodeploy54543
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000